
bind = SUPER SHIFT, Y, exec, $HOME/.local/share/LinuxMintHyprlandConfig/bin/custom-open-link.sh "https://www.youtube.com/" "$HOME/.local/share/LinuxMintHyprlandConfig/icon/youtube.png"

bind = SUPER SHIFT, A, exec, $HOME/.local/share/LinuxMintHyprlandConfig/bin/custom-open-link.sh "https://www.chatgpt.com/" "$HOME/.local/share/LinuxMintHyprlandConfig/icon/chatgpt.png"

bind = SUPER SHIFT, G, exec, $HOME/.local/share/LinuxMintHyprlandConfig/bin/custom-open-link.sh "https://gemini.google.com/" "$HOME/.local/share/LinuxMintHyprlandConfig/icon/google-gemini.png" 

# bind = SUPER SHIFT, C, exec, $HOME/.local/share/LinuxMintHyprlandConfig/bin/custom-open-link.sh "https://calendar.google.com/calendar/" "$HOME/.local/share/LinuxMintHyprlandConfig/icon/google-calendar.png"

bind = SUPER SHIFT, C, exec, $HOME/.local/share/LinuxMintHyprlandConfig/bin/custom-open-link.sh "https://claude.ai/" "$HOME/.local/share/LinuxMintHyprlandConfig/icon/claude.png"

bind = SUPER SHIFT, T, exec, $HOME/.local/share/LinuxMintHyprlandConfig/bin/custom-open-link.sh "https://tasks.google.com/" "$HOME/.local/share/LinuxMintHyprlandConfig/icon/google-tasks.png"

bind = SUPER SHIFT, L, exec, $HOME/.local/share/LinuxMintHyprlandConfig/bin/custom-open-link.sh "https://notebooklm.google.com/" "$HOME/.local/share/LinuxMintHyprlandConfig/icon/google-notebooklm.png"

bind = SUPER SHIFT, H, exec, $HOME/.local/share/LinuxMintHyprlandConfig/bin/custom-open-link.sh "https://web.whatsapp.com/" "$HOME/.local/share/LinuxMintHyprlandConfig/icon/whatsapp.png"

bind = SUPER SHIFT, U, exec, $HOME/.local/share/LinuxMintHyprlandConfig/bin/custom-open-link.sh "https://github.com/Avdhut-code/" "$HOME/.local/share/LinuxMintHyprlandConfig/icon/github-light.png"

bind = SUPER SHIFT, P, exec, $HOME/.local/share/LinuxMintHyprlandConfig/bin/custom-open-link.sh "https://www.perplexity.ai/" "$HOME/.local/share/LinuxMintHyprlandConfig/icon/perplexity.png"