# windowrulev2 = workspace 2,class:^(gnome-terminal)$

windowrulev2 = workspace 2,class:^(zen)$

windowrulev2 = workspace 4,class:^(nemo)$

windowrulev2 = workspace 3,class:^(code)$

windowrulev2 = workspace 3,class:^(evince)$

windowrulev2 = workspace 3,title:^(Picture-in-Picture)$

windowrulev2 = workspace 4,class:^(xed)$

windowrulev2 = workspace 5,class:^(gnome-calendar)$

windowrulev2 = workspace 6,class:^(obsidian)$

windowrulev2 = workspace 8,title:^(btop Moniter)$

windowrulev2 = workspace 10,class:^(mpv)$

# Wofi
windowrulev2 = float,class:^(wofi)$
windowrulev2 = center,class:^(wofi)$

# Exit confirmation window
windowrulev2 = float, title:^(Exit-hyprland-pass)$
windowrulev2 = center, title:^(Exit-hyprland-pass)$
windowrulev2 = size 800 100, title:^(Exit-hyprland-pass)$
windowrulev2 = noanim, title:^(Exit-hyprland-pass)$